//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIHDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntecedentesPatologicos
    {
        public int idAntecedentes { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public string AntecedentesPersonales { get; set; }
        public string AntecedentesFamiliares { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
