//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIHDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consulta()
        {
            this.ConsultaEstudioLaboratorio = new HashSet<ConsultaEstudioLaboratorio>();
            this.Ginecologia = new HashSet<Ginecologia>();
            this.Odontologia = new HashSet<Odontologia>();
            this.Pediatria = new HashSet<Pediatria>();
            this.Receta = new HashSet<Receta>();
        }
    
        public int idConsulta { get; set; }
        public Nullable<int> idTipoConsulta { get; set; }
        public Nullable<int> idSignosVitales { get; set; }
        public Nullable<int> idHistoriaClinica { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string sintomas { get; set; }
        public string diagnostico { get; set; }
        public string prescripcion { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> fum { get; set; }
    
        public virtual HistoriaClinica HistoriaClinica { get; set; }
        public virtual SignosVitales SignosVitales { get; set; }
        public virtual TipoConsulta TipoConsulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaEstudioLaboratorio> ConsultaEstudioLaboratorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ginecologia> Ginecologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odontologia> Odontologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pediatria> Pediatria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Receta { get; set; }
    }
}
