//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIHDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspecialidadProfesional
    {
        public int idEspecialidadProfesional { get; set; }
        public string especialidadProfesional1 { get; set; }
        public Nullable<System.DateTime> borrado { get; set; }
    }
}
