//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIHDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establecimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Establecimiento()
        {
            this.Farmacia = new HashSet<Farmacia>();
        }
    
        public int idEstablecimiento { get; set; }
        public Nullable<int> idParroquia { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string representanteLegal { get; set; }
        public string cedulaRepresentanteLegal { get; set; }
        public string redDeAtencion { get; set; }
        public string zona { get; set; }
        public string permisoDeFuncionamiento { get; set; }
        public string registroUnico { get; set; }
        public string logoUrl { get; set; }
        public Nullable<System.DateTime> borrado { get; set; }
    
        public virtual Parroquia Parroquia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farmacia> Farmacia { get; set; }
    }
}
