//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIHDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudioLaboratorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstudioLaboratorio()
        {
            this.ConsultaEstudioLaboratorio = new HashSet<ConsultaEstudioLaboratorio>();
        }
    
        public int idEstudioLaboratorio { get; set; }
        public Nullable<int> idCategoriaEstudioLaboratorio { get; set; }
        public string estudioLaboratorio1 { get; set; }
    
        public virtual CategoriaEstudioLaboratorio CategoriaEstudioLaboratorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaEstudioLaboratorio> ConsultaEstudioLaboratorio { get; set; }
    }
}
