//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIHDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentoHospitalizacion
    {
        public int idMedicamentoHospitalizacion { get; set; }
        public Nullable<int> idMedicamento { get; set; }
        public Nullable<int> idHospitalizacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string notasDeEvolucion { get; set; }
        public string prescripcionMedica { get; set; }
        public Nullable<System.DateTime> borrado { get; set; }
    
        public virtual Hospitalizacion Hospitalizacion { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
