//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIHDD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMHospitalDelDiaEntities : DbContext
    {
        public SMHospitalDelDiaEntities()
            : base("name=SMHospitalDelDiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AntecedentesPatologicos> AntecedentesPatologicos { get; set; }
        public virtual DbSet<Canton> Canton { get; set; }
        public virtual DbSet<CategoriaEstudioLaboratorio> CategoriaEstudioLaboratorio { get; set; }
        public virtual DbSet<CategoriaMedicamento> CategoriaMedicamento { get; set; }
        public virtual DbSet<CodigoCIE> CodigoCIE { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<CondicionEgreso> CondicionEgreso { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<ConsultaEstudioLaboratorio> ConsultaEstudioLaboratorio { get; set; }
        public virtual DbSet<Continente> Continente { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVenta { get; set; }
        public virtual DbSet<Entidad> Entidad { get; set; }
        public virtual DbSet<EspecialidadEgreso> EspecialidadEgreso { get; set; }
        public virtual DbSet<EspecialidadProfesional> EspecialidadProfesional { get; set; }
        public virtual DbSet<Establecimiento> Establecimiento { get; set; }
        public virtual DbSet<EstudioLaboratorio> EstudioLaboratorio { get; set; }
        public virtual DbSet<Farmacia> Farmacia { get; set; }
        public virtual DbSet<Ginecologia> Ginecologia { get; set; }
        public virtual DbSet<HistoriaClinica> HistoriaClinica { get; set; }
        public virtual DbSet<Hospitalizacion> Hospitalizacion { get; set; }
        public virtual DbSet<LinkArchivo> LinkArchivo { get; set; }
        public virtual DbSet<Medicamento> Medicamento { get; set; }
        public virtual DbSet<MedicamentoHospitalizacion> MedicamentoHospitalizacion { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Obstetricia> Obstetricia { get; set; }
        public virtual DbSet<Odontologia> Odontologia { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Parroquia> Parroquia { get; set; }
        public virtual DbSet<Path> Path { get; set; }
        public virtual DbSet<Pediatria> Pediatria { get; set; }
        public virtual DbSet<PermisoPerfil> PermisoPerfil { get; set; }
        public virtual DbSet<Precio> Precio { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Receta> Receta { get; set; }
        public virtual DbSet<ResultadoEstudioLaboratorio> ResultadoEstudioLaboratorio { get; set; }
        public virtual DbSet<SignosVitales> SignosVitales { get; set; }
        public virtual DbSet<subMenu> subMenu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoConsulta> TipoConsulta { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
