//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIHDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.AntecedentesPatologicos = new HashSet<AntecedentesPatologicos>();
            this.HistoriaClinica = new HashSet<HistoriaClinica>();
            this.Hospitalizacion = new HashSet<Hospitalizacion>();
            this.Obstetricia = new HashSet<Obstetricia>();
        }
    
        public int idPaciente { get; set; }
        public Nullable<int> idParroquia { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string direccion { get; set; }
        public string celular { get; set; }
        public string telefono { get; set; }
        public string genero { get; set; }
        public Nullable<System.DateTime> fecNacimiento { get; set; }
        public string etnia { get; set; }
        public string estadoCivil { get; set; }
        public string nacionalidad { get; set; }
        public string paisNacimiento { get; set; }
        public string discapacidad { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> borrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AntecedentesPatologicos> AntecedentesPatologicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriaClinica> HistoriaClinica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospitalizacion> Hospitalizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obstetricia> Obstetricia { get; set; }
        public virtual Parroquia Parroquia { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
