//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIHDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisoPerfil
    {
        public int idPermisoPerfil { get; set; }
        public Nullable<int> idPath { get; set; }
        public string idRol { get; set; }
        public Nullable<bool> selecciona { get; set; }
        public Nullable<bool> inserta { get; set; }
        public Nullable<bool> actualiza { get; set; }
        public Nullable<bool> elimina { get; set; }
        public Nullable<bool> mostrarEnMenu { get; set; }
        public Nullable<System.DateTime> borrado { get; set; }
    
        public virtual Path Path { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
    }
}
